"""empty message

Revision ID: 323f40859874
Revises: 73658ed54dee
Create Date: 2024-05-09 13:41:56.421225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323f40859874'
down_revision = '73658ed54dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isOfficiating', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isOfficiating')

    # ### end Alembic commands ###
