"""empty message

Revision ID: 73658ed54dee
Revises: 9aa67fc9dd05
Create Date: 2024-05-09 12:47:47.101707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73658ed54dee'
down_revision = '9aa67fc9dd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isOfficiatingHod', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isOfficiatingHod')

    # ### end Alembic commands ###
