"""empty message

Revision ID: 9aa67fc9dd05
Revises: c9a5e00b9cac
Create Date: 2024-04-16 01:34:27.893480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa67fc9dd05'
down_revision = 'c9a5e00b9cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejectedBy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.drop_column('rejectedBy')

    # ### end Alembic commands ###
